export type {
  Participant,
  Room,
  Message,
  MessageContent,
  CreateRoomRequest,
  CreateRoomResponse,
  ListRoomsResponse,
  GetRoomResponse,
  UpdateRoomRequest,
  UpdateRoomResponse,
  RoomHistoryResponse,
  RegisterParticipantRequest,
  RegisterParticipantResponse,
  GetParticipantResponse,
  UpdateParticipantRequest,
  UpdateParticipantResponse,
  GetMessageResponse,
} from '@opc/protocol';
