name: Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string
      retries:
        required: false
        type: number
        default: 0
        description: jest retry count for flaky tests on important branches

permissions:
  contents: read

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm + Node
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Download build artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: mobile-build-dist
          path: .

      - name: Run unit tests
        run: pnpm test
